name: "Deploy Practica"

on:
  push:
    brances: ["main"]

jobs:
  deploy-practica:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "pull code"
      - run: echo "correr migraciones"
      - run: echo "finalizado"